### ISSUE TITLE
DLsite Metadata download description

### ISSUE THREAD

**Issue by hellomynameisleo** [erri120/Playnite.Extensions#86]
When downloading the metadata it doesn't seem to fetch the description metadata from DLsite.

**Comment by erri120** [comment]
This is intended, check the README for all fields the Metadata Provider _provides_.

I've decided against getting the description mainly because I personally don't really care but secondly because I'm not sure about the state of things with Playnite. Before the rework Playnite accepted HTML and rendered that to WPF but there were talks of switching to Markdig for Markdown rendering. Previous versions of the Plugins just directly copied the HTML from the site which was not always very good. DLsite and F95zone, in that regard, don't have a clear cut short description field you can just copy but instead have sometimes massive blocks of HTML which you won't read anyways and look weird when rendered in Playnite.

I might think about only grabbing the text from the sites but for now you have to make due with no description. Remember that the Plugins add links to the original site so you can quickly open them anyways.
